// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WamBot.Twitch.Data;

namespace WamBot.Twitch.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStreamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("DbChannels");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannelUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStreamId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName", "ChannelName");

                    b.HasIndex("ChannelName");

                    b.ToTable("DbChannelUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbUser", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("OnyxPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenisOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenisType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("DbUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannelUser", b =>
                {
                    b.HasOne("WamBot.Twitch.Data.DbChannel", "DbChannel")
                        .WithMany("DbChannelUsers")
                        .HasForeignKey("ChannelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WamBot.Twitch.Data.DbUser", "DbUser")
                        .WithMany("DbChannelUsers")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbChannel");

                    b.Navigation("DbUser");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannel", b =>
                {
                    b.Navigation("DbChannelUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbUser", b =>
                {
                    b.Navigation("DbChannelUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
