// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WamBot.Twitch.Data;

namespace WamBot.Twitch.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class NpgsqlBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:twitch_name", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .UseCollation("twitch_name");

                    b.Property<string>("LastStreamId")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("DbChannels");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannelUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .UseCollation("twitch_name");

                    b.Property<string>("ChannelName")
                        .HasColumnType("text")
                        .UseCollation("twitch_name");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("LastStreamId")
                        .HasColumnType("text");

                    b.HasKey("UserName", "ChannelName");

                    b.HasIndex("ChannelName");

                    b.ToTable("DbChannelUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbUser", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .UseCollation("twitch_name");

                    b.Property<int>("AllTimeConsecutiveLosses")
                        .HasColumnType("integer");

                    b.Property<int>("AllTimeConsecutiveWins")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveLosses")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveWins")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("OnyxPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("PenisOffset")
                        .HasColumnType("integer");

                    b.Property<int>("PenisType")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.HasAlternateKey("Id");

                    b.ToTable("DbUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannelUser", b =>
                {
                    b.HasOne("WamBot.Twitch.Data.DbChannel", "DbChannel")
                        .WithMany("DbChannelUsers")
                        .HasForeignKey("ChannelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WamBot.Twitch.Data.DbUser", "DbUser")
                        .WithMany("DbChannelUsers")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbChannel");

                    b.Navigation("DbUser");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbChannel", b =>
                {
                    b.Navigation("DbChannelUsers");
                });

            modelBuilder.Entity("WamBot.Twitch.Data.DbUser", b =>
                {
                    b.Navigation("DbChannelUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
